# Generated by Django 5.0.7 on 2024-07-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('time', models.BigIntegerField()),
                ('recipeURL', models.TextField()),
                ('imageURL', models.TextField()),
            ],
        ),
    ]
